# Site
title:          "Matt Harrington"
description:    "Matt Harrington's Personal Website"
hero:           "Logical Mind | Playful Heart"
picture:        'assets/img/headshot.jpg'
locale:         en_US
url:            https://matt-harrington.com


# Github Pages
lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false


# Jekyll
permalink:      /:title/
markdown:       kramdown
highlighter:    rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed

# Social
email: harringtonswim@gmail.com
github: mattaharrington
linkedin: in/matt-harrington

#stackoverflow:
#facebook: username
#instagram: username
#dribbble: username
#youtube: username
#soundcloud: username


# Comments
disqus_shortname: alperenbozkurt-net

# Gems
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [ README.md,
  Gemfile,
  Gemfile.lock,
  node_modules,
  gulpfile.js,
  package.json,
  _site,
  src,
  vendor,
  CNAME,
  LICENSE,
  Rakefile ]
