# Site
title:          "Matt's Website"
bio:            "Matt's personal Website"
description:    "I spend my days bettering myself, hoping I'll impress my mom."
picture:        'assets/img/profile.png'
locale:         en_US
url:            https://matt-harrington.com


# Jekyll
permalink:      /:title/
markdown:       kramdown
highlighter:    rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed

# Social
email: harringtonswim@gmail.com
github: https://github.com/mattaharrington
linkedin: https://www.linkedin.com/in/matt-harrington/

#stackoverflow:
#facebook: username
#instagram: username
#dribbble: username
#youtube: username
#soundcloud: username


# Comments
disqus_shortname: alperenbozkurt-net


# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
